# Inspired by Jim Hester's Azure Pipelines tests
# https://github.com/jimhester/azuretest

trigger:
- master
- develop

pr:
- master
- develop
- release/*

jobs:
  - job: 'Build_all_vignettes'
    timeoutInMinutes: 4320
    pool: Default
    variables:
      R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
    container: satijalab/seurat-pkgdown:4.0.0-beta
    steps:
      - script: |
            Rscript --default-packages=stats,graphics,grDevices,utils,datasets,base,methods -e "install.packages('.', type = 'source', repos = NULL, dependencies = FALSE, lib = Sys.getenv('R_LIBS_USER'))"
            mv /data/* data/
            mkdir output
            mkdir output/images
            mkdir output/timings
            Rscript -e "pkgdown::init_site()"
            Rscript -e "pkgdown::build_article('pbmc3k_tutorial')"
            ls vignettes | grep -v 'pbmc3k_tutorial.Rmd' | grep -v 'assets' | grep -v 'vignettes.yaml' | cut -f 1 -d '.' | parallel -j4 "Rscript -e 'pkgdown::build_article(\"{}\")'"
            Rscript -e "pkgdown::build_site(lazy = TRUE)"
        displayName: 'Build pkgdown site'
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)'
          contents: '**/docs/**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/docs'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)/docs/docs/'
          artifactName: docs
